name: zenda
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  google_sign_in: ^6.2.1
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.39
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/images/
    - assets/icons/